# Generated by Django 2.0.7 on 2018-08-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodjaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_haj', models.TextField(blank=True, db_column='ID', null=True)),
                ('first_name', models.TextField(blank=True, db_column='FIRST_NAME', null=True)),
                ('season', models.TextField(blank=True, db_column='SEASON', null=True)),
                ('age', models.TextField(blank=True, db_column='AGE', null=True)),
                ('entry_date', models.TextField(blank=True, db_column='ENTRY_DATE', null=True)),
                ('exit_date', models.TextField(blank=True, db_column='EXIT_DATE', null=True)),
                ('entry_time', models.TextField(blank=True, db_column='ENTRY_TIME', null=True)),
                ('exit_time', models.TextField(blank=True, db_column='EXIT_TIME', null=True)),
                ('gender', models.TextField(blank=True, db_column='GENDER', null=True)),
                ('passport_issue_pla', models.TextField(blank=True, db_column='PASSPORT_ISSUE_PLA', null=True)),
                ('lk_visa_issue_plac', models.TextField(blank=True, db_column='LK_VISA_ISSUE_PLAC', null=True)),
                ('lk_nationality_des', models.TextField(blank=True, db_column='LK_NATIONALITY_DES', null=True)),
                ('lk_airline_name_le', models.TextField(blank=True, db_column='LK_AIRLINE_NAME_LE', null=True)),
            ],
            options={
                'db_table': 'hodjaj',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='benevole',
        ),
    ]
