# Generated by Django 2.0.7 on 2018-08-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hajjtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HajjData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hajj', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('season', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('entry_date', models.TextField(blank=True, null=True)),
                ('exit_date', models.TextField(blank=True, null=True)),
                ('entry_time', models.TextField(blank=True, null=True)),
                ('exit_time', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('passport_issue_pla', models.TextField(blank=True, null=True)),
                ('lk_visa_issue_plac', models.TextField(blank=True, null=True)),
                ('lk_nationality_des', models.TextField(blank=True, null=True)),
                ('lk_airline_name_le', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
