# Generated by Django 2.0.7 on 2018-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180802_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pas', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HajjDatta',
        ),
    ]
