# Generated by Django 2.0.7 on 2018-08-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180802_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hajj', models.IntegerField()),
                ('id_voluteer', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
