# Generated by Django 2.0.7 on 2018-08-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_emergency_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hajj', models.TextField()),
                ('id_volount', models.IntegerField()),
                ('date', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='emergency_cases',
        ),
    ]
