# Generated by Django 2.0.7 on 2018-08-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180803_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmrHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hajj_id', models.TextField()),
                ('voulont_id', models.IntegerField()),
                ('date', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='emergcase',
        ),
    ]
